version: '3.7'

services:

  postgres:
    container_name: 'examples.postgres'
    restart: always
    image: postgres
    build:
      context: ./
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=exampledb
    networks:
      - internal
  
  webapp:
    container_name: 'examples.app'
    restart: always
    image: web
    build:
      context: ./
      dockerfile: web.dockerfile
    ports:
    - "5000:80"
    links:
      - "postgres"
    networks:
      - internal

networks:
  internal:
    driver: bridge
